In [1]:
import pandas as pd
import numpy as np

In [33]:
# yellow
_thinking_and_feeling = {'besd1': 'How important do you think vaccines are for your children’s health?', 
                        'besd2': 'How safe do you think vaccines are for your children?',
                        'besd3' : 'How much do you trust the health workers who given children vaccines?'}
# green
_social_processes = {'besd4' : 'Do you think most parents you know get their children vaccinated?', 
                    'besd5' : 'Do you think most of your close family and friends want you to get your children vaccinated?',
                    'besd6' : ' Do you think your religious leaders want you to get your children vaccinated?',
                    'besd7' : 'Do you think your community leaders want you to get your children vaccinated?',
                    'besd8' : 'Has a health worker recommended your children be vaccinated?',
                    'besd9' : 'Have you ever been contacted about your children being due for vaccination?'}
# red
_motivation = {}
# blue
_practical_issues = {'besd10' : 'If it was time for your child to get vaccinated, would the mother need permission to take the child to the clinic?',
                    'besd11' : 'Do you know where to go to get your child vaccinated?',
                    'besd12' : 'Have you personally ever taken your child/children to get vaccinated?',
                    'besd13' : 'Have you ever been turned away when you tried to get your children vaccinated?',
                    'besd14' : 'How easy is it to get vaccination services for your children?',
                    'besd15' : 'How easy is it to pay for vaccination? When you think about the cost, please consider any payments to the clinic, the cost of getting there, plus the cost of taking time away from work.',
                    'besd17' : 'How satisfied are you with the vaccination services in the UK?'}

_thinking_and_feeling_description = {'besd1': 'Vaccines and children’s health', 
                        'besd2': 'Vaccines safe for children',
                        'besd3' : 'Trust in health workers who vaccinate'}
# green
_social_processes_description = {'besd4' : 'Most parents vaccinate their children', 
                    'besd5' : 'Family and friends want me to vaccinate',
                    'besd6' : 'Religious leaders want me to vaccinate',
                    'besd7' : 'Community leaders want me to vaccinate',
                    'besd8' : 'Health worker recommended vaccination?',
                    'besd9' : 'Have been contacted about vaccination'}
# red
_motivation_description = {}
# blue
_practical_issues_description = {'besd10' : 'Mother needs permission for clinic',
                    'besd11' : 'Know where to get child vaccinated',
                    'besd12' : 'Personally took child to vaccination',
                    'besd13' : 'Was turned away from vaccination',
                    'besd14' : 'How easy to get vaccination',
                    'besd15' : 'How easy to pay for vaccination',
                    'besd17' : 'How satisfied with vaccination services'}

thinking_and_feeling = list(_thinking_and_feeling.keys())
social_processes = list(_social_processes.keys())
motivation = list(_motivation.keys())
practical_issues = list(_practical_issues.keys())

def hex_to_rgb(hex_color):
    hex_color = hex_color.lstrip('#')
    return tuple(int(hex_color[i:i+2], 16) / 255.0 for i in (0, 2, 4))

alpha_besd_backgound = 0.7

_colors_besd  = {
'thinking_and_feeling' :  (*hex_to_rgb('#fbe7a3'), alpha_besd_backgound), # yellow
'social_processes': (*hex_to_rgb('#c9dfb9'), alpha_besd_backgound), # green
'motivation': (*hex_to_rgb('#f2b0ac'), alpha_besd_backgound), # red
'practical_issues': (*hex_to_rgb('#9fbee2'), alpha_besd_backgound) #blue
}

colors_besd = { b : _colors_besd['thinking_and_feeling'] for b in thinking_and_feeling}
colors_besd.update(  { b : _colors_besd['social_processes'] for b in social_processes} )
colors_besd.update(  { b : _colors_besd['practical_issues'] for b in practical_issues} )
colors_besd.update(  { b : _colors_besd['motivation'] for b in motivation} )

In [34]:
_besd_vars = thinking_and_feeling  + social_processes + practical_issues 
_besd_vars_capital = [f'BeSD{b[4:]}' for b in _besd_vars] 
_besd_description = list(_thinking_and_feeling.values()) + list(_social_processes.values()) + list(_practical_issues.values())
_besd_group = 3*['Thinking feeling'] + 6*['Social processes'] + 7*['Practical issues']
besd_description = pd.DataFrame(columns = ['Variable', 'Description', 'BeSD group'])
besd_description['Variable'] = _besd_vars_capital
besd_description['Description'] = _besd_description
besd_description['BeSD group'] = _besd_group
besd_description = besd_description.set_index('Variable')

In [35]:
besd_description

                                                Description        BeSD group
Variable
BeSD1     How important do you think vaccines are for yo...  Thinking feeling
BeSD2     How safe do you think vaccines are for your ch...  Thinking feeling
BeSD3     How much do you trust the health workers who g...  Thinking feeling
BeSD4     Do you think most parents you know get their c...  Social processes
BeSD5     Do you think most of your close family and fri...  Social processes
BeSD6      Do you think your religious leaders want you ...  Social processes
BeSD7     Do you think your community leaders want you t...  Social processes
BeSD8     Has a health worker recommended your children ...  Social processes
BeSD9     Have you ever been contacted about your childr...  Social processes
BeSD10    If it was time for your child to get vaccinate...  Practical issues
BeSD11    Do you know where to go to get your child vacc...  Practical issues
BeSD12    Have you personally ever taken your child/chil...  Practical issues
BeSD13    Have you ever been turned away when you tried ...  Practical issues
BeSD14    How easy is it to get vaccination services for...  Practical issues
BeSD15    How easy is it to pay for vaccination? When yo...  Practical issues
BeSD17    How satisfied are you with the vaccination ser...  Practical issues

In [36]:
besd_description_latex = besd_description.to_latex(index=True, escape=True)
print(besd_description_latex)

\begin{tabular}{lll}
\toprule
 & Description & BeSD group \\
Variable &  &  \\
\midrule
BeSD1 & How important do you think vaccines are for your children’s health? & Thinking feeling \\
BeSD2 & How safe do you think vaccines are for your children? & Thinking feeling \\
BeSD3 & How much do you trust the health workers who given children vaccines? & Thinking feeling \\
BeSD4 & Do you think most parents you know get their children vaccinated? & Social processes \\
BeSD5 & Do you think most of your close family and friends want you to get your children vaccinated? & Social processes \\
BeSD6 &  Do you think your religious leaders want you to get your children vaccinated? & Social processes \\
BeSD7 & Do you think your community leaders want you to get your children vaccinated? & Social processes \\
BeSD8 & Has a health worker recommended your children be vaccinated? & Social processes \\
BeSD9 & Have you ever been contacted about your children being due for vaccination? & Social processes \\
BeSD10 & If it was time for your child to get vaccinated, would the mother need permission to take the child to the clinic? & Practical issues \\
BeSD11 & Do you know where to go to get your child vaccinated? & Practical issues \\
BeSD12 & Have you personally ever taken your child/children to get vaccinated? & Practical issues \\
BeSD13 & Have you ever been turned away when you tried to get your children vaccinated? & Practical issues \\
BeSD14 & How easy is it to get vaccination services for your children? & Practical issues \\
BeSD15 & How easy is it to pay for vaccination? When you think about the cost, please consider any payments to the clinic, the cost of getting there, plus the cost of taking time away from work. & Practical issues \\
BeSD17 & How satisfied are you with the vaccination services in the UK? & Practical issues \\
\bottomrule
\end{tabular}

In [37]:
with open("../tables/besd_description_table.tex", "w") as file:
    file.write(besd_description_latex)

In [57]:
rct_description = pd.DataFrame(columns = ['Treatment group', 'Control/Treatment','Timing of Immunization','Additional information'])
rct_description['Treatment group'] = [f'RCT{i}' for i in range(7)]
rct_description['Control/Treatment'] = ['Control'] + ['Treatment'] * 6
rct_description['Timing of Immunization'] = ['-'] + ['Within a few days', 'Within a month', 'One month following birth'] * 2
rct_description['Additional information'] = ['-']*4 + ['Importance explained']*3
rct_description = rct_description.set_index('Treatment group')

In [58]:
rct_description

,Control/Treatment,Timing of Immunization,Additional information
Treatment group,,,
RCT0,Control,-,-
RCT1,Treatment,Within a few days,-
RCT2,Treatment,Within a month,-
RCT3,Treatment,One month following birth,-
RCT4,Treatment,Within a few days,Importance explained
RCT5,Treatment,Within a month,Importance explained
RCT6,Treatment,One month following birth,Importance explained

In [59]:
rct_description_latex = rct_description.to_latex(index=True, escape=True)
print(rct_description_latex)

\begin{tabular}{llll}
\toprule
 & Control/Treatment & Timing of Immunization & Additional information \\
Treatment group &  &  &  \\
\midrule
RCT0 & Control & - & - \\
RCT1 & Treatment & Within a few days & - \\
RCT2 & Treatment & Within a month & - \\
RCT3 & Treatment & One month following birth & - \\
RCT4 & Treatment & Within a few days & Importance explained \\
RCT5 & Treatment & Within a month & Importance explained \\
RCT6 & Treatment & One month following birth & Importance explained \\
\bottomrule
\end{tabular}

In [60]:
with open("../tables/rct_description_table.tex", "w") as file:
    file.write(rct_description_latex)

In [38]:
_survey = ['AGE','DIS','EMP','EDU','ETH','HEA','HHLAN','LAN','MIG','REG','SEX','YUK/BUK','OPC',
          'besd1','besd2','besd3','besd4','besd5','besd6','besd7','besd8','besd9','besd10','besd11','besd12','besd13','besd14','besd15','besd17',
          'X1_permission_ch_i', 'X1_sex_ch_i', 'X1_relationship_ch_i',
          'RCT','rsv_intent_hyp_pre', 'rsv_intent_hyp_post','X1_rsv_ch_i']

_ew_micro = ['resident_age_18m','disability_4a','economic_activity_status_15m','highest_qualification','ethnic_group_tb_20b','health_in_general','hh_language','main_language_detailed_10m',
            'migrant_ind','religion_tb','sex','year_arrival_uk/country_of_birth_10a','gltla22cd'] + ['-']*16 + ['-']*7

_ni_micro = ['AGEh','DISABILITY','ECOPUK11','HLQUPUK11', 'ETHNICITYNI_G', 'HEALTH','HHLDLANG11','MAINLANGgNI',
            'MOVEFROMg','RELIGIONNI','SEX','YRARRNIg/COBgNI','LA_CODE_2014'] + ['-']*16 + ['-']*7

_scot_micro = ['AGE','DISABILITY','ECOPUK11','HLQPS11','ETHNIC','HEALTH','-','LANGPS11',
              'MOVEFROM','RELPS11','SEX','YR_ARRIVALPUK11/COB','OUNCIL_AREA_GROUP'] + ['-']*16 + ['-']*7

_categorical_ordinal = ['categorical']*13 + ['ordinal']*3 + ['categorical']*10 + ['ordinal']*3 + ['categorical']*4 + ['ordinal']*3

_besd_group = ['-']*13 + 3*['Thinking feeling'] + 6*['Social processes'] + 7*['Practical issues'] + ['-']*7

_model_a = ['ind.']*6 + ['-'] + ['ind.']*6 + ['-']*16 + ['-']*4 + ['dep.'] + ['-']*2
_model_b = ['ind.']*6 + ['ind.'] + ['ind.']*6 + ['-']*16 + ['-']*4 + ['dep.'] + ['-']*2
_model_c = ['ind.']*6 + ['ind.'] + ['ind.']*6 + ['ind.']*16 + ['-']*4 + ['dep.'] + ['-']*2
_model_d = ['ind.']*6 + ['-'] + ['ind.']*6 + ['-']*16 + ['-']*3 + ['ind.'] +['dep.']*2 + ['-']
_model_e = ['ind.']*6 + ['-'] + ['ind.']*5 + ['-'] + ['-']*16 + ['ind.']*4 + ['dep.']*3

In [39]:
variables = ['Age','Disability', 'Economic activity', 'Education', 'Ethnicity','Health in general', 'Household Language', 'Language',
             'Migration', 'Religion','Sex','Year of arrival in UK/Born in the UK','ITL3 region',
             'BeSD1','BeSD2','BeSD3','BeSD4','BeSD5','BeSD6','BeSD7','BeSD8','BeSD9','BeSD10','BeSD11','BeSD12','BeSD13','BeSD14','BeSD15','BeSD17',
            'Permission needed to vaccinate child','Relation to child','Sex of child',
            'Randomized treatment group',
            'Hypothetical RSV intent pre', 'Hypothetical RSV intent post', 'RSV intent for own child']
columns = ['Variable','Survey','EW micros.', 'SCOT micros.', 'NI micros.','categorical/ordinal','BeSD group'] + ['Model A', 'Model B', 'Model C', 'Model D', 'Model E'] #,'Model','independent','dependent']
data_overview = pd.DataFrame( columns = columns)
data_overview['Variable'] = variables
data_overview['Survey'] = _survey
data_overview['categorical/ordinal'] = _categorical_ordinal
data_overview['BeSD group'] = _besd_group
data_overview['Model A'] = _model_a
data_overview['Model B'] = _model_b
data_overview['Model C'] = _model_c
data_overview['Model D'] = _model_d
data_overview['Model E'] = _model_e

data_overview['EW micros.'] = _ew_micro
data_overview['SCOT micros.'] = _scot_micro
data_overview['NI micros.'] = _ni_micro

data_overview = data_overview.set_index('Variable')
data_overview

,Survey,EW micros.,SCOT micros.,NI micros.,categorical/ordinal,BeSD group,Model A,Model B,Model C,Model D,Model E
Variable,,,,,,,,,,,
Age,AGE,resident_age_18m,AGE,AGEh,categorical,-,ind.,ind.,ind.,ind.,ind.
Disability,DIS,disability_4a,DISABILITY,DISABILITY,categorical,-,ind.,ind.,ind.,ind.,ind.
Economic activity,EMP,economic_activity_status_15m,ECOPUK11,ECOPUK11,categorical,-,ind.,ind.,ind.,ind.,ind.
Education,EDU,highest_qualification,HLQPS11,HLQUPUK11,categorical,-,ind.,ind.,ind.,ind.,ind.
Ethnicity,ETH,ethnic_group_tb_20b,ETHNIC,ETHNICITYNI_G,categorical,-,ind.,ind.,ind.,ind.,ind.
Health in general,HEA,health_in_general,HEALTH,HEALTH,categorical,-,ind.,ind.,ind.,ind.,ind.
Household Language,HHLAN,hh_language,-,HHLDLANG11,categorical,-,-,ind.,ind.,-,-
Language,LAN,main_language_detailed_10m,LANGPS11,MAINLANGgNI,categorical,-,ind.,ind.,ind.,ind.,ind.
Migration,MIG,migrant_ind,MOVEFROM,MOVEFROMg,categorical,-,ind.,ind.,ind.,ind.,ind.
Religion,REG,religion_tb,RELPS11,RELIGIONNI,categorical,-,ind.,ind.,ind.,ind.,ind.
Sex,SEX,sex,SEX,SEX,categorical,-,ind.,ind.,ind.,ind.,ind.
Year of arrival in UK/Born in the UK,YUK/BUK,year_arrival_uk/country_of_birth_10a,YR_ARRIVALPUK11/COB,YRARRNIg/COBgNI,categorical,-,ind.,ind.,ind.,ind.,ind.
ITL3 region,OPC,gltla22cd,OUNCIL_AREA_GROUP,LA_CODE_2014,categorical,-,ind.,ind.,ind.,ind.,-
BeSD1,besd1,-,-,-,ordinal,Thinking feeling,-,-,ind.,-,-
BeSD2,besd2,-,-,-,ordinal,Thinking feeling,-,-,ind.,-,-
BeSD3,besd3,-,-,-,ordinal,Thinking feeling,-,-,ind.,-,-
BeSD4,besd4,-,-,-,categorical,Social processes,-,-,ind.,-,-
BeSD5,besd5,-,-,-,categorical,Social processes,-,-,ind.,-,-
BeSD6,besd6,-,-,-,categorical,Social processes,-,-,ind.,-,-
BeSD7,besd7,-,-,-,categorical,Social processes,-,-,ind.,-,-
BeSD8,besd8,-,-,-,categorical,Social processes,-,-,ind.,-,-
BeSD9,besd9,-,-,-,categorical,Social processes,-,-,ind.,-,-
BeSD10,besd10,-,-,-,categorical,Practical issues,-,-,ind.,-,-
BeSD11,besd11,-,-,-,categorical,Practical issues,-,-,ind.,-,-
BeSD12,besd12,-,-,-,categorical,Practical issues,-,-,ind.,-,-
BeSD13,besd13,-,-,-,categorical,Practical issues,-,-,ind.,-,-
BeSD14,besd14,-,-,-,ordinal,Practical issues,-,-,ind.,-,-
BeSD15,besd15,-,-,-,ordinal,Practical issues,-,-,ind.,-,-
BeSD17,besd17,-,-,-,ordinal,Practical issues,-,-,ind.,-,-
Permission needed to vaccinate child,X1_permission_ch_i,-,-,-,categorical,-,-,-,-,-,ind.
Relation to child,X1_sex_ch_i,-,-,-,categorical,-,-,-,-,-,ind.
Sex of child,X1_relationship_ch_i,-,-,-,categorical,-,-,-,-,-,ind.
Randomized treatment group,RCT,-,-,-,categorical,-,-,-,-,ind.,ind.
Hypothetical RSV intent pre,rsv_intent_hyp_pre,-,-,-,ordinal,-,dep.,dep.,dep.,dep.,dep.
Hypothetical RSV intent post,rsv_intent_hyp_post,-,-,-,ordinal,-,-,-,-,dep.,dep.
RSV intent for own child,X1_rsv_ch_i,-,-,-,ordinal,-,-,-,-,-,dep.

In [45]:
# data_overview_latex = data_overview.to_latex(index=True, escape=True)
# don't need BeSD group as in previous table
data_overview_latex = data_overview.drop('BeSD group', axis = 1).to_latex(index=True, escape=True)
print(data_overview_latex)

\begin{tabular}{lllllllllll}
\toprule
 & Survey & EW micros. & SCOT micros. & NI micros. & categorical/ordinal & Model A & Model B & Model C & Model D & Model E \\
Variable &  &  &  &  &  &  &  &  &  &  \\
\midrule
Age & AGE & resident\_age\_18m & AGE & AGEh & categorical & ind. & ind. & ind. & ind. & ind. \\
Disability & DIS & disability\_4a & DISABILITY & DISABILITY & categorical & ind. & ind. & ind. & ind. & ind. \\
Economic activity & EMP & economic\_activity\_status\_15m & ECOPUK11 & ECOPUK11 & categorical & ind. & ind. & ind. & ind. & ind. \\
Education & EDU & highest\_qualification & HLQPS11 & HLQUPUK11 & categorical & ind. & ind. & ind. & ind. & ind. \\
Ethnicity & ETH & ethnic\_group\_tb\_20b & ETHNIC & ETHNICITYNI\_G & categorical & ind. & ind. & ind. & ind. & ind. \\
Health in general & HEA & health\_in\_general & HEALTH & HEALTH & categorical & ind. & ind. & ind. & ind. & ind. \\
Household Language & HHLAN & hh\_language & - & HHLDLANG11 & categorical & - & ind. & ind. & - & - \\
Language & LAN & main\_language\_detailed\_10m & LANGPS11 & MAINLANGgNI & categorical & ind. & ind. & ind. & ind. & ind. \\
Migration & MIG & migrant\_ind & MOVEFROM & MOVEFROMg & categorical & ind. & ind. & ind. & ind. & ind. \\
Religion & REG & religion\_tb & RELPS11 & RELIGIONNI & categorical & ind. & ind. & ind. & ind. & ind. \\
Sex & SEX & sex & SEX & SEX & categorical & ind. & ind. & ind. & ind. & ind. \\
Year of arrival in UK/Born in the UK & YUK/BUK & year\_arrival\_uk/country\_of\_birth\_10a & YR\_ARRIVALPUK11/COB & YRARRNIg/COBgNI & categorical & ind. & ind. & ind. & ind. & ind. \\
ITL3 region & OPC & gltla22cd & OUNCIL\_AREA\_GROUP & LA\_CODE\_2014 & categorical & ind. & ind. & ind. & ind. & - \\
BeSD1 & besd1 & - & - & - & ordinal & - & - & ind. & - & - \\
BeSD2 & besd2 & - & - & - & ordinal & - & - & ind. & - & - \\
BeSD3 & besd3 & - & - & - & ordinal & - & - & ind. & - & - \\
BeSD4 & besd4 & - & - & - & categorical & - & - & ind. & - & - \\
BeSD5 & besd5 & - & - & - & categorical & - & - & ind. & - & - \\
BeSD6 & besd6 & - & - & - & categorical & - & - & ind. & - & - \\
BeSD7 & besd7 & - & - & - & categorical & - & - & ind. & - & - \\
BeSD8 & besd8 & - & - & - & categorical & - & - & ind. & - & - \\
BeSD9 & besd9 & - & - & - & categorical & - & - & ind. & - & - \\
BeSD10 & besd10 & - & - & - & categorical & - & - & ind. & - & - \\
BeSD11 & besd11 & - & - & - & categorical & - & - & ind. & - & - \\
BeSD12 & besd12 & - & - & - & categorical & - & - & ind. & - & - \\
BeSD13 & besd13 & - & - & - & categorical & - & - & ind. & - & - \\
BeSD14 & besd14 & - & - & - & ordinal & - & - & ind. & - & - \\
BeSD15 & besd15 & - & - & - & ordinal & - & - & ind. & - & - \\
BeSD17 & besd17 & - & - & - & ordinal & - & - & ind. & - & - \\
Permission needed to vaccinate child & X1\_permission\_ch\_i & - & - & - & categorical & - & - & - & - & ind. \\
Relation to child & X1\_sex\_ch\_i & - & - & - & categorical & - & - & - & - & ind. \\
Sex of child & X1\_relationship\_ch\_i & - & - & - & categorical & - & - & - & - & ind. \\
Randomized treatment group & RCT & - & - & - & categorical & - & - & - & ind. & ind. \\
Hypothetical RSV intent pre & rsv\_intent\_hyp\_pre & - & - & - & ordinal & dep. & dep. & dep. & dep. & dep. \\
Hypothetical RSV intent post & rsv\_intent\_hyp\_post & - & - & - & ordinal & - & - & - & dep. & dep. \\
RSV intent for own child & X1\_rsv\_ch\_i & - & - & - & ordinal & - & - & - & - & dep. \\
\bottomrule
\end{tabular}

In [46]:
with open("../tables/data_overview_table.tex", "w") as file:
    file.write(data_overview_latex)